import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: "Dashboard | DNK",
  description: "Generated by create next app",
};
const dashboardlayout = ({ children }) => {
  return (
    <div>
      <div className="drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col items-center justify-center">
          {children}
          <label htmlFor="my-drawer-2" className="btn btn-primary drawer-button lg:hidden">
            Open drawer
          </label>
        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" aria-label="close sidebar" className="drawer-overlay"></label>
          <ul className="menu bg-blue-400 text-content text-white min-h-screen w-[250px] p-4">
            {/* Sidebar content here */}
            <li> <Link href='/dashboard'>User Profile</Link></li>
            <li> <Link href='/dashboard/show-order'>Show Order</Link></li>
            <hr />
            <li> <Link href='/'>Home</Link></li>
            <li> <Link href='/products'>Products</Link></li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default dashboardlayout;